version: "3.0"
services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ofek
      MONGO_INITDB_ROOT_PASSWORD: ofekgabay
    ports:
      - 27017:27017
    volumes:
      - ./config/mongod.conf:/etc/mongod.conf
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ofek
      ME_CONFIG_MONGODB_ADMINPASSWORD: ofekgabay
    depends_on:
      - mongo
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ofek
      POSTGRES_PASSWORD: ofekgabay
      POSTGRES_DB: air_port
      volumes: postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
volumes:
  postgres: ~
