version: "3"
services:
  server:
    build:
      context: .
      args:
        NPM_LOG_LEVEL: notice
    ports:
      - "${SERVER_PORT}:3000"
    environment:
      POSTGRESQL_URL: "postgres://${POSTGRESQL_USER}:${POSTGRESQL_PASSWORD}@db:5432"
      BCRYPT_SALT: "${BCRYPT_SALT}"
    depends_on:
      - mongo
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
  # db:
  #   image: postgres
  #   restart: always
  #   environment:
  #     POSTGRES_USER: ofek
  #     POSTGRES_PASSWORD: ofekgabay
  #     POSTGRES_DB: air_port
  #   volumes:
  #     - /Users/Ofek/Documents/postgresql:/var/lib/postgresql
  #   ports:
  #     - 5432:5432
  #     - migrate
  migrate:
    build:
      context: .
      args:
        NPM_LOG_LEVEL: notice
    command: npm run db:init
    working_dir: /app/server
    environment:
      POSTGRESQL_URL: "postgres://${POSTGRESQL_USER}:${POSTGRESQL_PASSWORD}@db:5432"
      BCRYPT_SALT: "${BCRYPT_SALT}"
    depends_on:
      - db
  db:
    image: postgres:12
    environment:
      POSTGRES_USER: ${POSTGRESQL_USER}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres: ~
